server:
  port: 8081
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/${database}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${name}
    password: ${pw}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      '[hibernate.default_batch_fetch-size]': 100

logging:
  level:
    '[com.example.bank]': INFO